# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
# title:            Matahi
tagline:          'My personal webpage'
# description:      'My personal webpage'
url:              http://cbio.ensmp.fr/~mmoarii

author:
  name:           'Matahi MOARII'
  url:            http://cbio.ensmp.fr/~mmoarii

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/matahi/matahi.github.io
